apiVersion: v1
kind: Service
metadata:
  name: demo-app-service
spec:
  selector:
    app: my-app
  ports:
    - protocol: TCP
      port: 8000    # port to expose to outside world
      targetPort: 8000  # container port 
  type: LoadBalancer
